{
 "title": "General Overview",
 "description": "General server metrics view: CPU, Memory, Network, Disk usages",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(monitoring_loadavg_load1, instance)"
   },
   {
    "name": "filesystems",
    "label": "filesystems",
    "query": "label_values(monitoring_filesystem_capacity_percent{instance=\"$instance\"}, mountpoint)"
   },
   { "name": "blockdevices", "label": "block device type", "query": "sd,nvme,vd,scsi,rbd,dm,cciss" },
   {
    "name": "netdevices",
    "label": "network devices",
    "query": "label_values(monitoring_netdev_rx_bytes_total{instance=\"$instance\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "tips", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "content": "#### use the selectors above to change tracked server, filesystems, and block devices, **but do not save your changes on exiting**\n\n*If you save changes when exiting, rainforests will burn. You do not want to burn rainforests.*\n\n##### Grafana tips\n\n* `Click` on metric names to isolate them\n* `SHIFT`+`Click` on metric names to disable them\n* `CTRL`+`Click` on metric names to toggle them\n* `CTRL`+`Click` or `CTRL`+`Drag` on metric graphs to annotate them\n* Use the timeframe button on top right to change the amount of viewed history\n* Click the \"tips\" row to collapse it"
  },
  { "title": "metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "current/latest", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "monitoring_uptime_seconds_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "monitoring_stat_cpu_current_usage_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "IOWait (%)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "monitoring_stat_cpu_current_iowait_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "IOPS, $blockdevices devices",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(monitoring_iostat_r{instance=\"$instance\",device=~\"($blockdevices).*\"} + monitoring_iostat_w{instance=\"$instance\",device=~\"($blockdevices).*\"}) without (device)"
    }
   ]
  },
  {
   "title": "Running Kernel Version",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "monitoring_kernel_version{instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Current Filesystem Utilization ($instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "monitoring_filesystem_capacity_percent{instance=\"$instance\",mountpoint=~\"$filesystems\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Established Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "monitoring_netstat_established_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "singlestat",
   "description": "The average of jobs that are in the run queue and in uninterruptible sleep",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "monitoring_loadavg_load1{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "history", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage & CPU IOwait ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "monitoring_stat_cpu_current_iowait_percent{instance=\"$instance\"}",
     "legendFormat": "IOWait"
    },
    {
     "expr": "monitoring_stat_cpu_current_usage_percent{instance=\"$instance\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "monitoring_stat_cpu_current_usage_percent{instance=\"$instance\"} >= 85",
     "legendFormat": "High CPU Usage"
    },
    {
     "expr": "monitoring_stat_cpu_current_iowait_percent{instance=\"$instance\"} >= 20",
     "legendFormat": "High CPU Iowait"
    },
    {
     "expr": "monitoring_stat_cpu_current_iowait_percent{instance=\"$instance\"} offset 1d",
     "legendFormat": "IOWait 1d"
    },
    {
     "expr": "monitoring_stat_cpu_current_usage_percent{instance=\"$instance\"} offset 1d",
     "legendFormat": "CPU 1d"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "monitoring_stat_cpu_current_usage_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Load Average ($instance)",
   "type": "graph",
   "description": "The average of jobs that are in the run queue and in uninterruptible sleep",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "monitoring_loadavg_load1{instance=\"$instance\"}",
     "legendFormat": "Load Average"
    },
    {
     "expr": "monitoring_loadavg_load1{instance=\"$instance\"} offset 1d",
     "legendFormat": "offset 1d"
    },
    {
     "expr": "monitoring_loadavg_load1{instance=\"$instance\"} offset 2d",
     "legendFormat": "offset 2d"
    }
   ]
  },
  {
   "title": "Average Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "monitoring_loadavg_load1{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage Per Mode ($instance)",
   "type": "graph",
   "description": "Computed via calculating an Instant Rate of Increase over 2 points in time",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "irate(monitoring_stat_cpu_seconds_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Disk Read/Write IOPS ($instance), $blockdevices devices",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(monitoring_iostat_r{instance=~\"$instance\",device=~\"($blockdevices).*\"}) without (device)",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(monitoring_iostat_w{instance=~\"$instance\",device=~\"($blockdevices).*\"}) without (device)",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Average IOPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(monitoring_iostat_r{instance=~\"$instance\"} + monitoring_iostat_w{instance=~\"$instance\"}) without (device)"
    }
   ]
  },
  {
   "title": "RX/TX Pkts ($instance), $netdevices devices",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(monitoring_netdev_rx_packets_total{instance=\"$instance\",device=~\"($netdevices).*\"}[5m])",
     "legendFormat": "RX {{ device }}"
    },
    {
     "expr": "irate(monitoring_netdev_tx_packets_total{instance=\"$instance\",device=~\"($netdevices).*\"}[5m])",
     "legendFormat": "TX {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Await ($instance), $blockdevices devices",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(monitoring_iostat_r_await{instance=\"$instance\",device=~\"($blockdevices).*\"}) without (device)",
     "legendFormat": "Read Await"
    },
    {
     "expr": "sum(monitoring_iostat_w_await{instance=\"$instance\",device=~\"($blockdevices).*\"}) without (device)",
     "legendFormat": "Write Await"
    }
   ]
  },
  {
   "title": "RX/TX Bits ($instance), $netdevices devices",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "irate(monitoring_netdev_rx_bytes_total{instance=\"$instance\",device=~\"($netdevices).*\"}[5m]) * 8",
     "legendFormat": "RX {{ device }}"
    },
    {
     "expr": "irate(monitoring_netdev_tx_bytes_total{instance=\"$instance\",device=~\"($netdevices).*\"}[5m]) * 8",
     "legendFormat": "TX {{ device }}"
    }
   ]
  },
  {
   "title": "Swap ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "monitoring_meminfo_swaptotal_kbytes{instance=\"$instance\"} - monitoring_meminfo_swapfree_kbytes{instance=\"$instance\"}",
     "legendFormat": "Estimated Used"
    },
    {
     "expr": "monitoring_meminfo_swaptotal_kbytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Jobs ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "monitoring_loadavg_jobs_background{instance=\"$instance\"}",
     "legendFormat": "Background Jobs"
    },
    {
     "expr": "monitoring_loadavg_jobs_running{instance=\"$instance\"}",
     "legendFormat": "Running Jobs"
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "monitoring_meminfo_memtotal_kbytes{instance=\"$instance\"} - monitoring_meminfo_memfree_kbytes{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "monitoring_meminfo_memtotal_kbytes{instance=\"$instance\"} - (monitoring_meminfo_memavailable_kbytes{instance=\"$instance\"} or (monitoring_meminfo_buffers_kbytes{instance=\"$instance\"} + monitoring_meminfo_cached_kbytes{instance=\"$instance\"} + monitoring_meminfo_memfree_kbytes{instance=\"$instance\"}))",
     "legendFormat": "Estimated Used"
    },
    {
     "expr": "monitoring_meminfo_memtotal_kbytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "monitoring_meminfo_committed_as_kbytes{instance=\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Established Connections ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "monitoring_netstat_established_total{instance=\"$instance\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Top 10 Slabs ($instance) (non-^size|dma|kmalloc)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, monitoring_slabinfo_objsize_bytes{instance=\"$instance\",slab!~\"^(size|dma|kmalloc).*\"})",
     "legendFormat": "{{ slab }}"
    }
   ]
  },
  {
   "title": "Filesystem Utilization Over Time ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "monitoring_filesystem_capacity_percent{instance=\"$instance\",mountpoint=~\"$filesystems\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  { "title": "stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Block Device Statistics (dashboard time range), $blockdevices devices",
   "type": "table",
   "description": "Some block device stats",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "avg_over_time(monitoring_iostat_util_percent{instance=\"$instance\",device=~\"($blockdevices).*\"}[$__range])",
     "legendFormat": "Average Utilization (24h)"
    },
    {
     "expr": "increase(monitoring_iostat_await{instance=\"$instance\",device=~\"($blockdevices).*\"}[$__range])",
     "legendFormat": "Total Await"
    },
    {
     "expr": "avg_over_time(monitoring_iostat_await{instance=\"$instance\",device=~\"($blockdevices).*\"}[$__range])",
     "legendFormat": "Average Await (24h)"
    },
    {
     "expr": "avg_over_time(monitoring_iostat_r{instance=\"$instance\",device=~\"($blockdevices).*\"}[$__range]) + avg_over_time(monitoring_iostat_w{instance=\"$instance\",device=~\"($blockdevices).*\"}[$__range])"
    },
    {
     "expr": "avg_over_time(monitoring_iostat_wmb{instance=\"$instance\",device=~\"($blockdevices).*\"}[$__range]) + avg_over_time(monitoring_iostat_rmb{instance=\"$instance\",device=~\"($blockdevices).*\"}[$__range])"
    }
   ]
  },
  {
   "title": "Network Device Statistics (dashboard time range), $blockdevices devices",
   "type": "table",
   "description": "Some net device stats",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "increase(monitoring_netdev_rx_bytes_total{instance=\"$instance\",device=~\"($netdevices).*\"}[$__range])",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "increase(monitoring_netdev_tx_bytes_total{instance=\"$instance\",device=~\"($netdevices).*\"}[$__range])"
    },
    {
     "expr": "increase(monitoring_netdev_rx_packets_total{instance=\"$instance\",device=~\"($netdevices).*\"}[$__range])"
    },
    {
     "expr": "increase(monitoring_netdev_tx_packets_total{instance=\"$instance\",device=~\"($netdevices).*\"}[$__range])"
    }
   ]
  }
 ]
}